<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>EducationPlatform</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\Application.csproj" />
      <ProjectReference Include="..\PostgreSql\PostgreSql.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="14.1.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Modules\Courses\DeleteCourse\" />
      <Folder Include="Modules\Courses\GetCourseById\" />
      <Folder Include="Modules\Courses\GetCourses\" />
      <Folder Include="Modules\Lessons\" />
      <Folder Include="Modules\Subscriptions\" />
    </ItemGroup>

</Project>
